export const cakes = [
    {
        id: 1,
        name: "Chocolate Truffle",
        description: "Rich chocolate cake .",
        price: 45,
        rating: 4.9,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 2,
        name: "Red Velvet",
        description: "Classic red velvet cake with cream cheese frosting.",
        price: 55,
        rating: 4.8,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 3,
        name: "Strawberry Bliss",
        description: "Fresh strawberry cake topped with whipped cream.",
        price: 50,
        rating: 4.7,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 4,
        name: "Black Forest",
        description: "Chocolate sponge layered with cherries and cream.",
        price: 60,
        rating: 4.9,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 5,
        name: "Blueberry Cheesecake",
        description: "Creamy cheesecake topped with blueberry compote.",
        price: 65,
        rating: 4.8,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 6,
        name: "Vanilla Delight",
        description: "Soft vanilla sponge with rich buttercream frosting.",
        price: 40,
        rating: 4.6,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 7,
        name: "Mango Paradise",
        description: "Refreshing mango cake made with real mango pulp.",
        price: 58,
        rating: 4.7,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 8,
        name: "Coffee Mocha",
        description: "Coffee-infused sponge layered with mocha cream.",
        price: 52,
        rating: 4.8,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 9,
        name: "Pineapple Delight",
        description: "Light sponge cake with pineapple cream layers.",
        price: 48,
        rating: 4.5,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 10,
        name: "Oreo Crunch",
        description: "Chocolate cake loaded with Oreo cookie crumbles.",
        price: 57,
        rating: 4.8,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 11,
        name: "KitKat Fantasy",
        description: "Chocolate cake decorated with KitKat bars.",
        price: 62,
        rating: 4.9,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 12,
        name: "Butterscotch Dream",
        description: "Moist butterscotch sponge with caramel drizzle.",
        price: 49,
        rating: 4.6,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 13,
        name: "Hazelnut Crunch",
        description: "Chocolate hazelnut cake with crunchy toppings.",
        price: 64,
        rating: 4.8,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 14,
        name: "Raspberry Velvet",
        description: "Velvety sponge layered with raspberry filling.",
        price: 59,
        rating: 4.7,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 15,
        name: "Caramel Indulgence",
        description: "Rich caramel cake topped with salted caramel.",
        price: 61,
        rating: 4.8,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 16,
        name: "Lemon Zest",
        description: "Tangy lemon sponge with citrus buttercream.",
        price: 46,
        rating: 4.5,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 17,
        name: "Chocolate Fudge",
        description: "Dense chocolate cake with fudge frosting.",
        price: 63,
        rating: 4.9,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 18,
        name: "Royal Fruit Cake",
        description: "Traditional fruit cake packed with dry fruits.",
        price: 68,
        rating: 4.7,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 19,
        name: "Chocolate Truffle",
        description: "Rich chocolate cake .",
        price: 45,
        rating: 4.9,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 20,
        name: "Red Velvet",
        description: "Classic red velvet cake with cream cheese frosting.",
        price: 55,
        rating: 4.8,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 21,
        name: "Strawberry Bliss",
        description: "Fresh strawberry cake topped with whipped cream.",
        price: 50,
        rating: 4.7,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 22,
        name: "Black Forest",
        description: "Chocolate sponge layered with cherries and cream.",
        price: 60,
        rating: 4.9,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 23,
        name: "Blueberry Cheesecake",
        description: "Creamy cheesecake topped with blueberry compote.",
        price: 65,
        rating: 4.8,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 24,
        name: "Vanilla Delight",
        description: "Soft vanilla sponge with rich buttercream frosting.",
        price: 40,
        rating: 4.6,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 25,
        name: "Mango Paradise",
        description: "Refreshing mango cake made with real mango pulp.",
        price: 58,
        rating: 4.7,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 26,
        name: "Coffee Mocha",
        description: "Coffee-infused sponge layered with mocha cream.",
        price: 52,
        rating: 4.8,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 27,
        name: "Pineapple Delight",
        description: "Light sponge cake with pineapple cream layers.",
        price: 48,
        rating: 4.5,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 28,
        name: "Oreo Crunch",
        description: "Chocolate cake loaded with Oreo cookie crumbles.",
        price: 57,
        rating: 4.8,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 29,
        name: "KitKat Fantasy",
        description: "Chocolate cake decorated with KitKat bars.",
        price: 62,
        rating: 4.9,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 30,
        name: "Butterscotch Dream",
        description: "Moist butterscotch sponge with caramel drizzle.",
        price: 49,
        rating: 4.6,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 31,
        name: "Hazelnut Crunch",
        description: "Chocolate hazelnut cake with crunchy toppings.",
        price: 64,
        rating: 4.8,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 32,
        name: "Raspberry Velvet",
        description: "Velvety sponge layered with raspberry filling.",
        price: 59,
        rating: 4.7,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 33,
        name: "Caramel Indulgence",
        description: "Rich caramel cake topped with salted caramel.",
        price: 61,
        rating: 4.8,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 34,
        name: "Lemon Zest",
        description: "Tangy lemon sponge with citrus buttercream.",
        price: 46,
        rating: 4.5,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 35,
        name: "Chocolate Fudge",
        description: "Dense chocolate cake with fudge frosting.",
        price: 63,
        rating: 4.9,
        image: "/cake-placeholder.jpg",
    },
    {
        id: 36,
        name: "Royal Fruit Cake",
        description: "Traditional fruit cake packed with dry fruits.",
        price: 68,
        rating: 4.7,
        image: "/cake-placeholder.jpg",
    },
];