import type {
  AuthenticatedMedusaRequest,
  MedusaResponse,
} from "@medusajs/framework/http"
import { ContainerRegistrationKeys } from "@medusajs/framework/utils"
import {
  resolveAdminFranchiseContext,
  type AuthenticatedTenantRequest,
} from "../../../utils/tenant-context"
import { provisionStoreLocation } from "../../../utils/provision-store-location"

// ---------------------------------------------------------------------------
// GET /admin/franchise-locations
// ---------------------------------------------------------------------------
export const GET = async (
  req: AuthenticatedMedusaRequest<undefined>,
  res: MedusaResponse
) => {
  const tenantReq = req as AuthenticatedTenantRequest
  const franchiseId = await resolveAdminFranchiseContext(tenantReq)

  const query = req.scope.resolve(ContainerRegistrationKeys.QUERY)
  const { data: locations } = await query.graph({
    entity: "store_location",
    fields: [
      "id",
      "name",
      "code",
      "address",
      "latitude",
      "longitude",
      "is_active",
      "is_accepting_orders",
      "is_default",
      "custom_lead_time_hours",
      "opening_hours",
      "daily_order_capacity",
      "franchise.id",
      "franchise.name",
      "created_at",
      "updated_at",
    ],
    filters: { franchise_id: franchiseId },
  })

  res.json({ locations })
}

// ---------------------------------------------------------------------------
// POST /admin/franchise-locations
// ---------------------------------------------------------------------------
interface CreateLocationBody {
  name: string
  address?: string
  latitude?: number
  longitude?: number
  is_active?: boolean
  is_accepting_orders?: boolean
  custom_lead_time_hours?: number
  daily_order_capacity?: number
  opening_hours?: Record<string, any>
  metadata?: Record<string, any>
}

export const POST = async (
  req: AuthenticatedMedusaRequest<CreateLocationBody>,
  res: MedusaResponse
) => {
  const tenantReq = req as AuthenticatedTenantRequest
  const franchiseId = await resolveAdminFranchiseContext(tenantReq)

  const {
    name,
    address,
    latitude,
    longitude,
    is_active,
    is_accepting_orders,
    custom_lead_time_hours,
    daily_order_capacity,
    opening_hours,
    metadata,
  } = req.body

  // Auth-scoped franchise; code is auto-generated by the shared helper.
  const result = await provisionStoreLocation(req.scope, {
    name,
    franchise_id: franchiseId,
    address: address ?? null,
    latitude: latitude ?? null,
    longitude: longitude ?? null,
    is_active,
    is_accepting_orders,
    custom_lead_time_hours,
    daily_order_capacity,
    opening_hours: opening_hours ?? null,
    metadata: metadata ?? null,
  })

  res.status(201).json({
    store_location: result.store_location,
    stock_location: result.stock_location,
    // Backward-compatible alias
    location: result.store_location,
  })
}
